name: Deploy from Develop Branch
on:
  push:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: npm install

      - name: Build
        run: npm run build
        env:
          REACT_APP_PREFIX: ${{ secrets.REACT_APP_PREFIX }}

      - name: Upload to FTP
        uses: sebastianpopp/ftp-action@releases/v2
        with:
          host: ${{ secrets.DEVELOP_FTP_SERVER }}
          user: ${{ secrets.DEVELOP_FTP_USERNAME }}
          password: ${{ secrets.DEVELOP_FTP_PASSWORD }}
          localDir: "build"
          remoteDir: ${{ secrets.DEVELOP_FTP_PATH}}
