name: Deploy from Develop PR
on:
  pull_request:
    branches: [ develop ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: npm install
        
      - name: build
        run: npm build
        env:
          REACT_APP_PREFIX: ${{ secrets.REACT_APP_PREFIX }}
        
      - name: Upload to FTP
        uses: sebastianpopp/ftp-action@releases/v2
        with:
          host: ${{ secrets.PREVIEW_FTP_SERVER }}
          user: ${{ secrets.PREVIEW_FTP_USERNAME }}
          password: ${{ secrets.PREVIEW_FTP_PASSWORD }}
          localDir: "/build"
          remoteDir: "/animes-react-preview.epizy.com/htdocs"
